name: Checks

on:
  push:
    branches:
      - main  # Specify the branch to trigger this action

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Compose Services
        run: docker-compose build

      - name: Run Tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run Linter
        run: docker-compose run --rm app sh -c "flake8"
